name: "Terraform"

on:
  push:
    branches: [ "main" ]
    paths:
      - "terraform/**"
      - ".github/workflows/terraform.yml"
  pull_request:
    branches: [ "main" ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    permissions:
      contents: read
      id-token: write

    env:
      TF_VAR_project: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_mqtt_broker_url: ${{ secrets.MQTT_BROKER_URL }}
      TF_VAR_mqtt_username: ${{ secrets.MQTT_USERNAME }}
      TF_VAR_mqtt_password: ${{ secrets.MQTT_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 'latest'

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ secrets.TFSTATE_BUCKET_NAME }}"

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false